# Generated by Django 3.2.25 on 2026-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.URLField(max_length=500),
        ),
    ]
